#!/usr/bin/bash

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
HOMEDIR=$(eval echo "~`whoami`")

if [ ! -z $SECURE_FILES ]; then
    # have to use  us-east-1 - aws tool does not recognize anything else
    # for S3 download
    sudo docker run --rm \
        -v ${HOMEDIR}:/data/ behance/docker-aws-s3-downloader \
         us-east-1 $CONTROL_TIER_S3SECURE_BUCKET $SECURE_FILES

    # must chown all files to core for use
    FILES=(${SECURE_FILES//:/ })
    for file in "${FILES[@]}"; do
        PIECES=(${file//,/ })
        S3FILE=${PIECES[0]}
        PERMS=${PIECES[1]}
        TARGET=${PIECES[2]}

        if [ "${TARGET}" == "" ]; then
            TARGET="${S3FILE}"
        fi

        sudo chown -R `whoami`:`whoami` ${HOMEDIR}/${TARGET}
    done
fi

# ensure that we have a public key for our RSA key and that it's authorized
if [ -f /home/`whoami`/.ssh/id_rsa ]; then
    ssh-keygen -f /home/`whoami`/.ssh/id_rsa -y > /home/`whoami`/.ssh/id_rsa.pub
    cat /home/`whoami`/.ssh/id_rsa.pub >> /home/`whoami`/.ssh/authorized_keys
fi

# ignore requests against github.com
# TODO: maybe...re-evaluate this
echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ${HOMEDIR}/.ssh/config

# Just bootstrap the environment and don't worry about potential changes from
# the setup scripts or updates from profile.d. The following setup steps are
# just unit files, which should use the EnvironmentFile systemd option, so
# this is just here to catch any simple assumptions made by the setup scripts
if [ -f /etc/environment ]; then
    source /etc/environment
fi

# profile.d
if [ ! -d /etc/profile.d ]; then
    sudo mkdir /etc/profile.d
fi
sudo cp ${SCRIPTDIR}/v2/profile.d/* /etc/profile.d/.

if [ -f /etc/environment ]; then
    source /etc/environment
fi

# TODO: come up with better way of doing this
if [ "${NODE_ROLE}" != "control" ]; then
    sudo cp ${SCRIPTDIR}/v2/non-control-profile.d/* /etc/profile.d/.
fi

# run all setup scripts
for script in $(ls ${SCRIPTDIR}/v2/setup)
do
    sudo /bin/bash ${SCRIPTDIR}/v2/setup/${script}
done

# fleet units that require AZs
AZ=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
for unit in $(ls ${SCRIPTDIR}/v2/fleet-az)
do
    sudo fleetctl submit "${SCRIPTDIR}/v2/fleet-az/${unit}"
    sudo fleetctl start ${unit}@${AZ}
done

# start generic fleet units
for unit in $(ls ${SCRIPTDIR}/v2/fleet)
do
    sudo fleetctl submit ${SCRIPTDIR}/v2/fleet/${unit}
    sudo fleetctl start ${unit}
done
